### ISSUE TITLE
如何忽略多余的训练标签

### ISSUE THREAD

**Issue by luhairong11** [CongWeilin/mtcnn-caffe#20]
你好，训练人脸检测的时候是3部分训练数据，2个任务进行的，非人脸，人脸，部分人脸，分类标签分别为0，1，-1，请问如何忽略掉-1的分类标签进行分类训练呢，又是如何忽略掉非人脸的回归标签进行回归任务训练的呢，期待您的解答，谢谢~

**Comment by CongWeilin** [comment]
you can check the Q&A
