### ISSUE TITLE
why do y-flip when training cls-task?

### ISSUE THREAD

**Issue by bpf476499866** [CongWeilin/mtcnn-caffe#38]
Hello and sorry to bother you.
I'v noticed that you randomly flipped the image before sending them into classification-trainer (pythonlayer.py, line 162+)：
... 
if random.choice([0,1])==1:
		im = cv2.flip(im,random.choice([-1,0,1]))
...
——I understand to do left-right-flip (or even rotate it) can increase the number of data, and make classifier robuster;
——But I guess to do a y-flip (or x-y-flip) dose no good to training a classifier, unless it will meet many revolved faces in the future.

**Comment by CongWeilin** [comment]
actually, my caffemodel do not use y flip because wider face do not fit it.
but y flip can make model more robust

**Comment by bpf476499866** [comment]
obliged to recive your answer!!
