### ISSUE TITLE
slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by yungs2017** [CongWeilin/mtcnn-caffe#55]
There was an error when I ran the "gen_12net_data.py" file
`File "gen_12net_data.py", line 98, in <module>
    cropped_im = img[ny1 : ny2, nx1 : nx2, :]
TypeError: slice indices must be integers or None or have an __index__ method
`
it seems that the indices should be integers but not float
so...?

**Comment by BobLiu20** [comment]
@yungs2017  Please change this code:
cropped_im = img[ny1 : ny2, nx1 : nx2, :]
to
cropped_im = img[int(ny1) : int(ny2), int(nx1) : int(nx2), :]

Since new numpy version request all slice indices must be intergers but not float.

**Comment by yungs2017** [comment]
Thanks, it works😀
